---
- hosts: all
  vars_files:
    - vars.yml
  tasks:
    - set_fact:
        list: "{{hostvars[inventory_hostname]['group_names'] | intersect(hostvars.keys())}}"
    - debug: var=hostvars.vars_cache[item]['thing']
      with_items: list
