---
- hosts: localhost
  vars:
      simple_version: "1.2.3"
      complex_version: "1.8.2-el7.centos"
  tasks:
      - assert:
          that:
              - simple_version | version_compare("1.3.0", "<=")
              - simple_version | version_compare("1.2.3", "==")
              - complex_version | version_compare("1.9", "<=")
